### ISSUE TITLE
Need Documentation Upload Here

### ISSUE THREAD

**Issue by kmh654** [kmh654/CM_Class#1]
Read the summary -_-

**Comment by Warriser1101** [comment]
Still an issue _-_

**Comment by kmh654** [comment]
Documentation has been posted in a ZIP file as of yesterday, updated the name of the file as it did not appear to be of importance

**Comment by Warriser1101** [comment]
I hope the lab is open this week. If not do to the lateness of this upload we might not be able to make the part. If that ends up being the case it falls on your teams. Just a heads up

**Comment by kmh654** [comment]
Labs will most likely be open this week, my team was having issues uploading documents till I could assist them on that Sunday. I'm sorry for the delay and wish you the best of luck re-creating our design.
